# 一般存储在`~/.cache/huggingface/accelerate/default_config.yaml`
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU  # 使用多个GPU参与的分布式训练
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0  # 当前机器的序号为0，注意这个值在不同机器上也是不同的
main_process_ip: 172.17.0.3  # 主进程的ip地址，可以通过`hostname -I`命令查询
main_process_port: 25006  # 主进程任意空闲端口均可
main_training_function: main
mixed_precision: 'no'
num_machines: 2  # 总共有两台机器参与训练
num_processes: 4  # 总共有4个GPU参与训练
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
